version: "3.9"
services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    container_name: backend
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
